/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JFrame;



/**
 *
 * @author Pedro
 */
public class AdministradorBoard extends javax.swing.JFrame {

    /**
     * Creates new form AdministradorBoard
     */
    public AdministradorBoard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        imageAvatar1 = new pedro.swing.ImageAvatar();
        admNome = new javax.swing.JLabel();
        adminl = new javax.swing.JLabel();
        admNome1 = new javax.swing.JLabel();
        btVisao = new com.pedro.swing.win_button.ButtonMenu();
        buttonMenu1 = new com.pedro.swing.win_button.ButtonMenu();
        buttonMenu2 = new com.pedro.swing.win_button.ButtonMenu();
        buttonMenu3 = new com.pedro.swing.win_button.ButtonMenu();
        jPanel3 = new javax.swing.JPanel();
        btMin = new com.pedro.swing.win_button.Button();
        btSair = new com.pedro.swing.win_button.Button();
        btMessagens = new com.pedro.swing.win_button.ButtonBadges();
        buttonBadges1 = new com.pedro.swing.win_button.ButtonBadges();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 65, 130));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/perfil.gif"))); // NOI18N
        jPanel2.add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 70));

        admNome.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        admNome.setForeground(new java.awt.Color(255, 255, 255));
        admNome.setText("C.O.U");
        jPanel2.add(admNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 40, 20));

        adminl.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        adminl.setForeground(new java.awt.Color(255, 255, 255));
        adminl.setText("Admin");
        adminl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminlMouseEntered(evt);
            }
        });
        jPanel2.add(adminl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 20));

        admNome1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        admNome1.setForeground(new java.awt.Color(255, 255, 255));
        admNome1.setText("Pedro Manjate");
        jPanel2.add(admNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 110, 20));

        btVisao.setBackground(new java.awt.Color(51, 51, 255));
        btVisao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/1.png"))); // NOI18N
        btVisao.setText("Visao geral");
        btVisao.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btVisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVisaoActionPerformed(evt);
            }
        });
        jPanel2.add(btVisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, 50));

        buttonMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/2.png"))); // NOI18N
        buttonMenu1.setText("Gestao de Staff");
        buttonMenu1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        buttonMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenu1ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 200, 50));

        buttonMenu2.setBackground(new java.awt.Color(255, 255, 255));
        buttonMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/3.png"))); // NOI18N
        buttonMenu2.setText("Definicoes  data Base");
        buttonMenu2.setActionCommand("Definicoes DaTa Base");
        buttonMenu2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        buttonMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenu2ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 200, 50));

        buttonMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/4.png"))); // NOI18N
        buttonMenu3.setText("Relatorios");
        buttonMenu3.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        buttonMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMenu3ActionPerformed(evt);
            }
        });
        jPanel2.add(buttonMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 230, 550));

        jPanel3.setBackground(new java.awt.Color(51, 65, 130));
        jPanel3.setFocusTraversalPolicyProvider(true);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btMin.setBackground(new java.awt.Color(218, 218, 3));
        btMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMinActionPerformed(evt);
            }
        });
        jPanel3.add(btMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 20));

        btSair.setBackground(new java.awt.Color(221, 3, 3));
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        jPanel3.add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        btMessagens.setBackground(new java.awt.Color(102, 102, 255));
        btMessagens.setForeground(new java.awt.Color(255, 0, 0));
        btMessagens.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/message.png"))); // NOI18N
        btMessagens.setBadges(5);
        btMessagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMessagensActionPerformed(evt);
            }
        });
        jPanel3.add(btMessagens, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 50, 40));

        buttonBadges1.setBackground(new java.awt.Color(51, 51, 255));
        buttonBadges1.setForeground(new java.awt.Color(255, 0, 0));
        buttonBadges1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/noti.png"))); // NOI18N
        buttonBadges1.setAutoscrolls(true);
        buttonBadges1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges1ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonBadges1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 50, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 40));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 630, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMinActionPerformed
  this.setState(JFrame.ICONIFIED);
             
    }//GEN-LAST:event_btMinActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
     System.exit(0);
    }//GEN-LAST:event_btSairActionPerformed

    private void buttonBadges1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBadges1ActionPerformed

    private void btMessagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMessagensActionPerformed
 btMessagens.setBadges(btMessagens.getBadges()+1);
    }//GEN-LAST:event_btMessagensActionPerformed

    private void btVisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVisaoActionPerformed
          VisaoGeral p1 = new VisaoGeral();
   p1.setSize(630,540);
   p1.setLocation(0,0);
   
   content.removeAll();
        content.add(p1, BorderLayout.CENTER );
  content.revalidate();
  content.repaint();
    
    }//GEN-LAST:event_btVisaoActionPerformed

    private void buttonMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenu1ActionPerformed
    GerirStaff p1 = new GerirStaff();
   p1.setSize(630,540);
   p1.setLocation(0,0);
   
   content.removeAll();
        content.add(p1, BorderLayout.CENTER );
  content.revalidate();
  content.repaint();
            // TODO add your handling code here:
    }//GEN-LAST:event_buttonMenu1ActionPerformed

    private void adminlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminlMouseEntered
     
    }//GEN-LAST:event_adminlMouseEntered

    private void buttonMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenu2ActionPerformed
GerirBaseDados p1 = new GerirBaseDados();
   p1.setSize(630,540);
   p1.setLocation(0,0);
   
   content.removeAll();
        content.add(p1, BorderLayout.CENTER );
  content.revalidate();
  content.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMenu2ActionPerformed

    private void buttonMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMenu3ActionPerformed
Relatorios p1 = new Relatorios();
   p1.setSize(630,540);
   p1.setLocation(0,0);
   
   content.removeAll();
        content.add(p1, BorderLayout.CENTER );
  content.revalidate();
  content.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonMenu3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admNome;
    private javax.swing.JLabel admNome1;
    private javax.swing.JLabel adminl;
    private com.pedro.swing.win_button.ButtonBadges btMessagens;
    private com.pedro.swing.win_button.Button btMin;
    private com.pedro.swing.win_button.Button btSair;
    private com.pedro.swing.win_button.ButtonMenu btVisao;
    private com.pedro.swing.win_button.ButtonBadges buttonBadges1;
    private com.pedro.swing.win_button.ButtonMenu buttonMenu1;
    private com.pedro.swing.win_button.ButtonMenu buttonMenu2;
    private com.pedro.swing.win_button.ButtonMenu buttonMenu3;
    private javax.swing.JPanel content;
    private pedro.swing.ImageAvatar imageAvatar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
