/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

/**
 *
 * @author Pedro
 */
public class VisaoGeral extends javax.swing.JPanel {

    /**
     * Creates new form VisaoGeral
     */
    public VisaoGeral() {
        initComponents();
        graf1.setValueWithAnimation(40);
         graf2.setValueWithAnimation(3);
          graf3.setValueWithAnimation(87);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graf1 = new com.pedro.chart.GaugeChart();
        jLabel1 = new javax.swing.JLabel();
        graf2 = new com.pedro.chart.GaugeChart();
        graf3 = new com.pedro.chart.GaugeChart();
        lineChart1 = new com.pedro.chart.LineChart();

        setBackground(new java.awt.Color(51, 65, 130));
        setPreferredSize(new java.awt.Dimension(630, 540));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        graf1.setBackground(new java.awt.Color(0, 0, 255));
        graf1.setAutoscrolls(true);
        add(graf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 68, 175, 146));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Painel Financeiro");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 22, -1, 28));

        graf2.setFont(new java.awt.Font("Roboto Medium", 1, 20)); // NOI18N
        add(graf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 68, 182, 156));
        add(graf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 68, 167, 178));
        add(lineChart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, 210));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.pedro.chart.GaugeChart graf1;
    private com.pedro.chart.GaugeChart graf2;
    private com.pedro.chart.GaugeChart graf3;
    private javax.swing.JLabel jLabel1;
    private com.pedro.chart.LineChart lineChart1;
    // End of variables declaration//GEN-END:variables
}
