/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin;

import View.ADMFrame;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.ui.FlatRoundBorder;
import com.formdev.flatlaf.ui.FlatTextBorder;
import java.awt.Color;
import static java.awt.SystemColor.text;
import java.awt.Toolkit;
import java.util.Date;
import javax.swing.border.Border;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Pedro
 */
public class AddFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form AddFuncionario
     */
    public AddFuncionario(JFrame fr) {
        initComponents();
      dateChooser1.setTextRefernce(txData);
        //---------------------------------------------------
        Border f = new FlatRoundBorder();
        pTxEmail1.setBorder(f);
          Border E = new FlatTextBorder();
        this.setBorder(E);
        //---------------------------------Validacao de textField
          AbstractDocument doc = (AbstractDocument) txSalario.getDocument();
        doc.setDocumentFilter(new DocumentFilter() {
            @Override
            public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.matches("\\d*")) { // Verifica se newText contém apenas dígitos
                    super.replace(fb, offset, length, text, attrs);
                } else {
                    // Se o texto não for numérico, não faça nada
                    Toolkit.getDefaultToolkit().beep(); // Emita um som de erro
                }
            }
        });
        
        
  //--------------------------------------------------------------------
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooser1 = new com.raven.datechooser.DateChooser();
        jLabel3 = new javax.swing.JLabel();
        pTxEmail1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        txData = new javax.swing.JTextField();
        txNome = new textfield.TextField();
        txApelido = new textfield.TextField();
        textField3 = new textfield.TextField();
        txSalario = new textfield.TextField();
        txContacto = new textfield.TextField();
        txEmail = new textfield.TextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imageAvatar1 = new pedro.swing.ImageAvatar();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Dados Pessoais :");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 30));

        pTxEmail1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pTxEmail1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 50, 30));

        txData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txDataActionPerformed(evt);
            }
        });
        pTxEmail1.add(txData, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        add(pTxEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 290, 50));

        txNome.setToolTipText("Nome");
        txNome.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txNome.setLabelText("Nome");
        add(txNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 290, 50));

        txApelido.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txApelido.setLabelText("Apelido");
        add(txApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        textField3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        textField3.setLabelText("Numero De Identidade");
        add(textField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 290, 50));

        txSalario.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txSalario.setLabelText("Salario");
        add(txSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 290, -1));

        txContacto.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txContacto.setLabelText("Contacto :");
        txContacto.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                txContactoComponentShown(evt);
            }
        });
        add(txContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 290, -1));

        txEmail.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txEmail.setLabelText("E-Mail");
        add(txEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 290, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexo", "Masculino", "Feminino" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 290, 50));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nacionalidade", " " }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 282, 290, 50));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado Civil", "Casado/a ", "Solteiro/a", "Viuvo/a", "Divorciado/a" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, 50));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoria", "Gerente", "Vendedor", "Outro", " ", " " }));
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 290, 50));

        jButton2.setText("Salvar");
        jButton2.setBorder(new FlatRoundBorder());
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 180, -1));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/user.png"))); // NOI18N
        add(imageAvatar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 110, 100));

        jLabel1.setText("Foto");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 30, -1));

        jTextField1.setText("FileChooser");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 240, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dateChooser1.showPopup();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txDataActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
JOptionPane.showConfirmDialog(dateChooser1, "Salvar?");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txContactoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txContactoComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_txContactoComponentShown

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.datechooser.DateChooser dateChooser1;
    private pedro.swing.ImageAvatar imageAvatar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel pTxEmail1;
    private textfield.TextField textField3;
    private textfield.TextField txApelido;
    private textfield.TextField txContacto;
    private javax.swing.JTextField txData;
    private textfield.TextField txEmail;
    private textfield.TextField txNome;
    private textfield.TextField txSalario;
    // End of variables declaration//GEN-END:variables
public  Color a ;

}
