/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ViewFuncionario;

import Controller.GerenteController;
import DAO.ImagemDirectorioDAO;
import DAO.StockTaxasDao;
import Model.Carro;
import Model.Funcionario;
import Model.ImagemDirectorios;
import Model.StockeTaxas;
import Model.Venda;
import java.awt.BorderLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Celso Mongane
 */
public class EfectuarVenda extends javax.swing.JPanel {
      int courent=0;
      DefaultTableModel model;
     ArrayList<Carro> sellectAllCarros ;
     Carro carro;
       ArrayList<ImageIcon> icon ;
     Base frame;
      Funcionario funcionario;
    public EfectuarVenda(Base frame, Funcionario funcionario) throws SQLException, ClassNotFoundException {
       this.funcionario = funcionario;
       this.frame =frame;
        initComponents();
        
        
        GerenteController cc = new GerenteController(frame);
                sellectAllCarros = cc.sellectAllCarros();
                model = new DefaultTableModel();
		model.addColumn("Marca");
		model.addColumn("modelo");
		model.addColumn("Numero de Chassi");
		model.addColumn("Numero do Motor");
		model.addColumn("Preco");
		model.addColumn("Estado");
		model.addColumn("cor");
		
                
                Table.setModel(model);
                
                  for(Carro c : sellectAllCarros){
        
        model.addRow(new Object[] {   c.getFabricante(), c.getModelo(),c.getNumChassi(),c.getNumMotor(),c.getPreco(), c.isVendido(), "sem cor" });
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        btSelect = new javax.swing.JButton();
        Voltar1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fotoCarro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lbPreco = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Base3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setText("Selecinar o veiculo");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 20));

        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Table);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 873, 224));

        btSelect.setText("Selecionar o veiculo");
        btSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btSelectMouseEntered(evt);
            }
        });
        btSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectActionPerformed(evt);
            }
        });
        jPanel5.add(btSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 223, -1));

        Voltar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/datechooser/previous.png"))); // NOI18N
        Voltar1.setText("Back");
        Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Voltar1ActionPerformed(evt);
            }
        });
        jPanel5.add(Voltar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel7.setText("Veiculos disponiveis");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 140, -1));

        fotoCarro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fotoCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/galery_image_phot.png"))); // NOI18N
        fotoCarro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(fotoCarro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 530, 340));
        fotoCarro.getAccessibleContext().setAccessibleName("");
        fotoCarro.getAccessibleContext().setAccessibleDescription("");

        jButton1.setText("Foto Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jButton2.setText("Proxima Foto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, -1, -1));

        lb1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jPanel5.add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 330, 50));

        lb2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jPanel5.add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 330, 50));

        lbPreco.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jPanel5.add(lbPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 270, 50));

        Base3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));

        add(Base3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Voltar1ActionPerformed
       
        Base3.removeAll();
    }//GEN-LAST:event_Voltar1ActionPerformed

    private void btSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectActionPerformed
         FormularioDoCliente form = new FormularioDoCliente(carro, funcionario, frame);
               frame.getBase2()
.setLayout(new BorderLayout());
               frame.getBase2()
.removeAll();
               frame.getBase2()
.add(form);
               frame.getBase2()
.revalidate();
               frame.getBase2()
.repaint();
        
        
    }//GEN-LAST:event_btSelectActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
    courent= 0;
    carro = null; 
    for(int j=0;j<sellectAllCarros.size();j++){
        if(Table.isRowSelected(j)){
            int numChassi = sellectAllCarros.get(j).getNumChassi();
            carro= sellectAllCarros.get(j);
            btSelect.setEnabled(true);
            ImagemDirectorioDAO dao = new ImagemDirectorioDAO();
            ArrayList<ImagemDirectorios> openFile = dao.openFile("Imagens");
            for(int k=0;k<openFile.size();k++){
            if(openFile.get(k).getChassi()==numChassi){
            
     icon  =       openFile.get(k).getCarroImagens();
     
     fotoCarro.setIcon(icon.get(courent));
            }
            
            }
            StockTaxasDao dao1 = new StockTaxasDao();
            ArrayList<StockeTaxas> openFile1 = dao1.openFile();
            Venda venda = new Venda(openFile1.get(0));
            venda.setCarro(sellectAllCarros.get(j));
            lb1.setText(sellectAllCarros.get(j).getFabricante()+" "+sellectAllCarros.get(j).getModelo()+" "+ sellectAllCarros.get(j).getAnoDeFabrico());
            lb2.setText("Com uma caixa "+sellectAllCarros.get(j).getTracao()+" "+" Motor a "+sellectAllCarros.get(j).getTipoDeComustivel());
            lbPreco.setText("Custa Apenas "+ venda.precoFinalSemPrestacoes() );
        
        }
        }
    }//GEN-LAST:event_TableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(icon!=null&&courent<icon.size()-1){
    courent++;
    fotoCarro.setIcon(icon.get(courent));
    }else{
            JOptionPane.showMessageDialog(frame, "sem Fotos", "Erro ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(icon!=null&&courent>0){
    courent--;
    fotoCarro.setIcon(icon.get(courent));
    }else{
            JOptionPane.showMessageDialog(frame, "sem Fotos", "Erro ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btSelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btSelectMouseEntered
       if(carro==null){
       btSelect.setEnabled(false);}
    }//GEN-LAST:event_btSelectMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base3;
    private javax.swing.JTable Table;
    private javax.swing.JButton Voltar1;
    private javax.swing.JButton btSelect;
    private javax.swing.JLabel fotoCarro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lbPreco;
    // End of variables declaration//GEN-END:variables
}
