
package ViewFuncionario;

import Model.Venda;
import java.util.Calendar;

/**
 *
 * @author Pedro
 */
public class Recibo extends javax.swing.JPanel {

    Venda venda;
    public Recibo(Venda venda) {
      this.venda = venda;
        initComponents();
        lb1.setText("Acp Car Solucions");
        lb2.setText("Recibo da venda do Veiculo : "+ venda.getCarro().getFabricante()+" "+venda.getCarro().getModelo()+" "+venda.getCarro().getAnoDeFabrico());
         lb3.setText("Cliente : "+ venda.getCliente().getNome()+ venda.getCliente().getApelido());
        
        if(venda.getTipoDePagamento().equalsIgnoreCase("Avista")){
      lb4.setText(" Vai pagar 'Avista ' "+venda.getPrecoDaVenda()+" MZN "+" Imposto, Taxas Inclusos ");
      }else{
          lb4.setText(" Vai pagar Por Prestacoes "+venda.getPrecoDaVenda()+" MZN "+ venda.getPrecoDaVenda()+ " MZN");
          
        }
        
        Calendar c = Calendar.getInstance();
     lb5.setText(c.getTime().toString());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lb3 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        lb4 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lb5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        jLabel1.setText("Factura & Recibo");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 34, -1, 46));

        lb3.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lb3.setText("c");
        add(lb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 690, 71));

        lb1.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lb1.setText("a");
        add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 690, 71));

        lb4.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lb4.setText("d");
        add(lb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 690, 71));

        lb2.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lb2.setText("b");
        add(lb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 690, 71));

        lb5.setFont(new java.awt.Font("Courier New", 0, 18)); // NOI18N
        lb5.setText("e");
        add(lb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 690, 71));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jTextField1.setText("||||||||||||||||||||");
        jTextField1.setBorder(null);
        jTextField1.setFocusable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 290, 30));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Courier New", 0, 24)); // NOI18N
        jTextField2.setText("||||||||||||||||||||");
        jTextField2.setBorder(null);
        jTextField2.setFocusable(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 280, 30));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 20)); // NOI18N
        jLabel2.setText("xxxxxxxxxxxxxxxxxxxxxxx");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 533, 290, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JLabel lb3;
    private javax.swing.JLabel lb4;
    private javax.swing.JLabel lb5;
    // End of variables declaration//GEN-END:variables
}
