/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.BorderLayout;
import java.awt.Color;

/**
 *
 * @author Pedro
 */
public class AdminFrame extends javax.swing.JFrame {

int xMouse, yMouse;
    public AdminFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painelMenu = new javax.swing.JPanel();
        admNome = new javax.swing.JLabel();
        adminl = new javax.swing.JLabel();
        admNome1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        menuContent = new javax.swing.JPanel();
        btgsatff = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btVG = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btGDB = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btR = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        label = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        button1 = new com.pedro.swing.win_button.Button();
        button2 = new com.pedro.swing.win_button.Button();
        buttonBadges1 = new com.pedro.swing.win_button.ButtonBadges();
        buttonBadges2 = new com.pedro.swing.win_button.ButtonBadges();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelMenu.setBackground(new java.awt.Color(51, 65, 130));
        painelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admNome.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        admNome.setForeground(new java.awt.Color(255, 255, 255));
        admNome.setText("C.O.U");
        painelMenu.add(admNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 40, 20));

        adminl.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        adminl.setForeground(new java.awt.Color(255, 255, 255));
        adminl.setText("Admin");
        adminl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminlMouseEntered(evt);
            }
        });
        painelMenu.add(adminl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 20));

        admNome1.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        admNome1.setForeground(new java.awt.Color(255, 255, 255));
        admNome1.setText("Pedro Manjate");
        painelMenu.add(admNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 100, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/user.png"))); // NOI18N
        painelMenu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 130, 140));

        menuContent.setBackground(new java.awt.Color(51, 65, 130));
        menuContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btgsatff.setBackground(new java.awt.Color(49, 63, 128));
        btgsatff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btgsatffMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btgsatffMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btgsatffMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/2.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("Gestao de Staff");

        javax.swing.GroupLayout btgsatffLayout = new javax.swing.GroupLayout(btgsatff);
        btgsatff.setLayout(btgsatffLayout);
        btgsatffLayout.setHorizontalGroup(
            btgsatffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btgsatffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        btgsatffLayout.setVerticalGroup(
            btgsatffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btgsatffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btgsatffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuContent.add(btgsatff, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 180, 40));

        btVG.setBackground(new java.awt.Color(51, 65, 130));
        btVG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVGMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btVGMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btVGMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/1.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("Visao Geral");

        javax.swing.GroupLayout btVGLayout = new javax.swing.GroupLayout(btVG);
        btVG.setLayout(btVGLayout);
        btVGLayout.setHorizontalGroup(
            btVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btVGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        btVGLayout.setVerticalGroup(
            btVGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btVGLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuContent.add(btVG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 40));

        btGDB.setBackground(new java.awt.Color(51, 65, 130));
        btGDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGDBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btGDBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btGDBMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/3.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 255, 255));
        jLabel8.setText("Gerir Base Dados");

        javax.swing.GroupLayout btGDBLayout = new javax.swing.GroupLayout(btGDB);
        btGDB.setLayout(btGDBLayout);
        btGDBLayout.setHorizontalGroup(
            btGDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btGDBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        btGDBLayout.setVerticalGroup(
            btGDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btGDBLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btGDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuContent.add(btGDB, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 180, -1));

        btR.setBackground(new java.awt.Color(51, 65, 130));
        btR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btRMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/4.png"))); // NOI18N

        label.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        label.setForeground(new java.awt.Color(204, 255, 255));
        label.setText("Relatorios");

        javax.swing.GroupLayout btRLayout = new javax.swing.GroupLayout(btR);
        btR.setLayout(btRLayout);
        btRLayout.setHorizontalGroup(
            btRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btRLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btRLayout.setVerticalGroup(
            btRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btRLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addContainerGap())
        );

        menuContent.add(btR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, 40));

        painelMenu.add(menuContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 310));

        jPanel1.add(painelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 230, 620));

        jPanel3.setBackground(new java.awt.Color(51, 65, 130));
        jPanel3.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.setFocusTraversalPolicyProvider(true);
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel3MouseDragged(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel3MousePressed(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        button1.setBackground(new java.awt.Color(255, 0, 0));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel3.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 20));

        button2.setBackground(new java.awt.Color(255, 204, 0));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel3.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 30, 20));

        buttonBadges1.setBackground(new java.awt.Color(51, 65, 130));
        buttonBadges1.setForeground(new java.awt.Color(255, 255, 255));
        buttonBadges1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/message.png"))); // NOI18N
        buttonBadges1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges1ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonBadges1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 70, 40));

        buttonBadges2.setBackground(new java.awt.Color(51, 65, 130));
        buttonBadges2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard/icon/noti.png"))); // NOI18N
        buttonBadges2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBadges2ActionPerformed(evt);
            }
        });
        jPanel3.add(buttonBadges2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 50, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, -1));

        content.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 1000, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel3MousePressed

    private void jPanel3MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseDragged

    private void buttonBadges2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges2ActionPerformed

        noti p1 = new noti();
        p1.setSize(1000, 620);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER );
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_buttonBadges2ActionPerformed

    private void buttonBadges1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBadges1ActionPerformed

        mess p1 = new mess();
        p1.setSize(1000, 620);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER );
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_buttonBadges1ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        this.setState( ICONIFIED);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        System.exit(0);

    
    }//GEN-LAST:event_button1ActionPerformed

    private void btGDBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGDBMouseExited

        btGDB.setBackground(painelMenu.getBackground());
        // TODO add your handling code here:
    }//GEN-LAST:event_btGDBMouseExited

    private void btGDBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGDBMouseEntered
        btGDB.setBackground(Color.black);
        btgsatff.setBackground(painelMenu.getBackground());
        btVG.setBackground(painelMenu.getBackground());
        // btGDB.setBackground(painelMenu.getBackground());
        btR.setBackground(painelMenu.getBackground()); // TODO add your handling code here:
    }//GEN-LAST:event_btGDBMouseEntered

    private void btGDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGDBMouseClicked
        GerirBaseDados p1 = new GerirBaseDados();
        p1.setSize(1000, 620);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER );
        content.revalidate();
        content.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_btGDBMouseClicked

    private void btRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRMouseExited
        btR.setBackground(painelMenu.getBackground());

        // TODO add your handling code here:
    }//GEN-LAST:event_btRMouseExited

    private void btRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRMouseEntered
        btR.setBackground(Color.black);
        btgsatff.setBackground(painelMenu.getBackground());
        btVG.setBackground(painelMenu.getBackground());
        btGDB.setBackground(painelMenu.getBackground());
        //  btR.setBackground(painelMenu.getBackground()); // TODO add your handling code here:
    }//GEN-LAST:event_btRMouseEntered

    private void btRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        // TODO add your handling code here:
        Relatorios p1 = new Relatorios();
        p1.setSize(1000, 620);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER );
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btRMouseClicked

    private void btVGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVGMouseExited

        btVG.setBackground(painelMenu.getBackground());

        // TODO add your handling code here:
    }//GEN-LAST:event_btVGMouseExited

    private void btVGMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVGMouseEntered
        btVG.setBackground(Color.black);
        // TODO add your handling code here:
        btgsatff.setBackground(painelMenu.getBackground());
        // btVG.setBackground(painelMenu.getBackground());
        btGDB.setBackground(painelMenu.getBackground());
        btR.setBackground(painelMenu.getBackground());
    }//GEN-LAST:event_btVGMouseEntered

    private void btVGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVGMouseClicked
        VisaoGeral p1 = new VisaoGeral();
        p1.setSize(1000, 620);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER );
        content.revalidate();
        content.repaint();
        // TODO add your handling code here:
    }//GEN-LAST:event_btVGMouseClicked

    private void btgsatffMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btgsatffMouseExited

        btgsatff.setBackground(painelMenu.getBackground());
    }//GEN-LAST:event_btgsatffMouseExited

    private void btgsatffMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btgsatffMouseEntered

        btgsatff.setBackground(Color.BLACK);
        // btgsatff.setBackground(new Color(51,65,130));// TODO add your handling code here:
        btVG.setBackground(painelMenu.getBackground());
        btGDB.setBackground(painelMenu.getBackground());
        btR.setBackground(painelMenu.getBackground());
    }//GEN-LAST:event_btgsatffMouseEntered

    private void btgsatffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btgsatffMouseClicked
        // TODO add your handling code here:
        GerirStaff p1 = new GerirStaff();
        p1.setSize(1000, 620);
        p1.setLocation(0,0);
        content.removeAll();
        content.add(p1, BorderLayout.CENTER );
        content.revalidate();
        content.repaint();
    }//GEN-LAST:event_btgsatffMouseClicked

    private void adminlMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminlMouseEntered

    }//GEN-LAST:event_adminlMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admNome;
    private javax.swing.JLabel admNome1;
    private javax.swing.JLabel adminl;
    private javax.swing.JPanel btGDB;
    private javax.swing.JPanel btR;
    private javax.swing.JPanel btVG;
    private javax.swing.JPanel btgsatff;
    private com.pedro.swing.win_button.Button button1;
    private com.pedro.swing.win_button.Button button2;
    private com.pedro.swing.win_button.ButtonBadges buttonBadges1;
    private com.pedro.swing.win_button.ButtonBadges buttonBadges2;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel label;
    private javax.swing.JPanel menuContent;
    private javax.swing.JPanel painelMenu;
    // End of variables declaration//GEN-END:variables
}
