/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Gerente;

import java.awt.Color;
import java.awt.Toolkit;
import java.util.Calendar;
import javax.swing.border.Border;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;

/**
 *
 * @author Pedro
 */
public class AdicionarCarro extends javax.swing.JPanel {

    /**
     * Creates new form AdicionarCarro
     */
    public AdicionarCarro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTxMarca = new javax.swing.JPanel();
        txMarca = new javax.swing.JTextField();
        lMarca = new javax.swing.JLabel();
        pTxModelo = new javax.swing.JPanel();
        txModelo = new javax.swing.JTextField();
        lModelo = new javax.swing.JLabel();
        lTitle = new javax.swing.JLabel();
        pTxAnoDeFabrico = new javax.swing.JPanel();
        txAnoDeFabrico = new javax.swing.JTextField();
        lAnoDeFabrico = new javax.swing.JLabel();
        pTxPreco = new javax.swing.JPanel();
        txPreco = new javax.swing.JTextField();
        lPreco = new javax.swing.JLabel();
        lMZN = new javax.swing.JLabel();
        pCTipCOmbus1 = new javax.swing.JPanel();
        lTipCombus1 = new javax.swing.JLabel();
        cCategoria = new combo_suggestion.ComboBoxSuggestion();
        pCTipCOmbus = new javax.swing.JPanel();
        lTipCombus = new javax.swing.JLabel();
        cTipCombustivel = new combo_suggestion.ComboBoxSuggestion();
        pCTipCOmbus2 = new javax.swing.JPanel();
        lTipCombus2 = new javax.swing.JLabel();
        cTracao = new combo_suggestion.ComboBoxSuggestion();
        pTxNumMotor = new javax.swing.JPanel();
        txNumMotor = new javax.swing.JTextField();
        lNumMotor = new javax.swing.JLabel();
        pTxNumChassi = new javax.swing.JPanel();
        txNumchassi = new javax.swing.JTextField();
        lNumChassi = new javax.swing.JLabel();
        pTxPreco1 = new javax.swing.JPanel();
        txPreco1 = new javax.swing.JTextField();
        lPreco1 = new javax.swing.JLabel();
        lMZN1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Adicionar Veiculo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto Medium", 0, 18))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pTxMarca.setBackground(new java.awt.Color(255, 255, 255));
        pTxMarca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxMarca.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txMarca.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txMarca.setBorder(null);
        txMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txMarcaFocusLost(evt);
            }
        });
        pTxMarca.add(txMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, 30));

        lMarca.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lMarca.setText("Marca :");
        lMarca.setToolTipText("");
        pTxMarca.add(lMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 30));

        add(pTxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 300, 50));

        pTxModelo.setBackground(new java.awt.Color(255, 255, 255));
        pTxModelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxModelo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txModelo.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txModelo.setBorder(null);
        txModelo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txModeloFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txModeloFocusLost(evt);
            }
        });
        pTxModelo.add(txModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, 30));

        lModelo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lModelo.setText("Modelo :");
        lModelo.setToolTipText("");
        pTxModelo.add(lModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        add(pTxModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 300, 50));

        lTitle.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lTitle.setText("Dados do veiculo");
        lTitle.setToolTipText("");
        add(lTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 150, 30));
        lTitle.getAccessibleContext().setAccessibleName("Dados do Veiculo");

        pTxAnoDeFabrico.setBackground(new java.awt.Color(255, 255, 255));
        pTxAnoDeFabrico.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxAnoDeFabrico.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txAnoDeFabrico.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txAnoDeFabrico.setBorder(null);
        txAnoDeFabrico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txAnoDeFabricoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txAnoDeFabricoFocusLost(evt);
            }
        });
        txAnoDeFabrico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txAnoDeFabricoKeyTyped(evt);
            }
        });
        pTxAnoDeFabrico.add(txAnoDeFabrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, 30));

        lAnoDeFabrico.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lAnoDeFabrico.setText("Ano de Fabrico :");
        lAnoDeFabrico.setToolTipText("");
        pTxAnoDeFabrico.add(lAnoDeFabrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        add(pTxAnoDeFabrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 50));

        pTxPreco.setBackground(new java.awt.Color(255, 255, 255));
        pTxPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxPreco.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txPreco.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txPreco.setBorder(null);
        txPreco.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txPrecoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txPrecoFocusLost(evt);
            }
        });
        txPreco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txPrecoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPrecoKeyTyped(evt);
            }
        });
        pTxPreco.add(txPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 100, 30));

        lPreco.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lPreco.setText("Preco de Aquisicao :");
        lPreco.setToolTipText("");
        pTxPreco.add(lPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        lMZN.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lMZN.setText("MZN");
        lMZN.setToolTipText("");
        pTxPreco.add(lMZN, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 30));

        add(pTxPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 300, 50));

        pCTipCOmbus1.setBackground(new java.awt.Color(255, 255, 255));
        pCTipCOmbus1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pCTipCOmbus1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTipCombus1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lTipCombus1.setText("Categoria");
        lTipCombus1.setToolTipText("");
        pCTipCOmbus1.add(lTipCombus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        cCategoria.setEditable(false);
        cCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "suv", "caminhao", "van", "bus", "dunner" }));
        cCategoria.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        pCTipCOmbus1.add(cCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, -1));

        add(pCTipCOmbus1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 300, 50));

        pCTipCOmbus.setBackground(new java.awt.Color(255, 255, 255));
        pCTipCOmbus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pCTipCOmbus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTipCombus.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lTipCombus.setText("Tipo de Combustivel");
        lTipCombus.setToolTipText("");
        pCTipCOmbus.add(lTipCombus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 30));

        cTipCombustivel.setEditable(false);
        cTipCombustivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gasolina", "Disel", "Gas", "Eletrico", "Hibrido" }));
        cTipCombustivel.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        pCTipCOmbus.add(cTipCombustivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 10, 140, -1));

        add(pCTipCOmbus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 300, 50));

        pCTipCOmbus2.setBackground(new java.awt.Color(255, 255, 255));
        pCTipCOmbus2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pCTipCOmbus2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lTipCombus2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lTipCombus2.setText("Tracao");
        lTipCombus2.setToolTipText("");
        pCTipCOmbus2.add(lTipCombus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 30));

        cTracao.setEditable(false);
        cTracao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manual", "Automatico" }));
        cTracao.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        pCTipCOmbus2.add(cTracao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, -1));

        add(pCTipCOmbus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 300, 50));

        pTxNumMotor.setBackground(new java.awt.Color(255, 255, 255));
        pTxNumMotor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxNumMotor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txNumMotor.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txNumMotor.setBorder(null);
        txNumMotor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txNumMotorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txNumMotorFocusLost(evt);
            }
        });
        txNumMotor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNumMotorKeyTyped(evt);
            }
        });
        pTxNumMotor.add(txNumMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, 30));

        lNumMotor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lNumMotor.setText("Numero De motor");
        lNumMotor.setToolTipText("");
        pTxNumMotor.add(lNumMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        add(pTxNumMotor, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 300, 50));

        pTxNumChassi.setBackground(new java.awt.Color(255, 255, 255));
        pTxNumChassi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxNumChassi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txNumchassi.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txNumchassi.setBorder(null);
        txNumchassi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txNumchassiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txNumchassiFocusLost(evt);
            }
        });
        txNumchassi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNumchassiKeyTyped(evt);
            }
        });
        pTxNumChassi.add(txNumchassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 140, 30));

        lNumChassi.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lNumChassi.setText("Numero de Chassi");
        lNumChassi.setToolTipText("");
        pTxNumChassi.add(lNumChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 30));

        add(pTxNumChassi, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 300, 50));

        pTxPreco1.setBackground(new java.awt.Color(255, 255, 255));
        pTxPreco1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxPreco1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txPreco1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txPreco1.setBorder(null);
        txPreco1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txPreco1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txPreco1FocusLost(evt);
            }
        });
        txPreco1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txPreco1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPreco1KeyTyped(evt);
            }
        });
        pTxPreco1.add(txPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 90, 30));

        lPreco1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lPreco1.setText("Kilometros Percoridos");
        lPreco1.setToolTipText("");
        pTxPreco1.add(lPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        lMZN1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lMZN1.setText("KM");
        lMZN1.setToolTipText("");
        pTxPreco1.add(lMZN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, 30));

        add(pTxPreco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 300, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txMarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txMarcaFocusGained
        Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(20, 0, 200));
        lMarca.setForeground(new java.awt.Color(20, 0, 200));
        txMarca.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200),2);

        pTxMarca.setBorder(b);
    }//GEN-LAST:event_txMarcaFocusGained

    private void txMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txMarcaFocusLost
        javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0));
        txMarca.setBorder(null);
        lMarca.setForeground(new java.awt.Color(0, 0, 0));
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
        pTxMarca.setBorder(b);
    }//GEN-LAST:event_txMarcaFocusLost

    private void txModeloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txModeloFocusGained
       Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(20, 0, 200));
        lModelo.setForeground(new java.awt.Color(20, 0, 200));
        txModelo.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200),2);

        pTxModelo.setBorder(b);
    }//GEN-LAST:event_txModeloFocusGained

    private void txModeloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txModeloFocusLost
        javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0));
        txModelo.setBorder(null);
        lModelo.setForeground(new java.awt.Color(0, 0, 0));
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
        pTxModelo.setBorder(b);
    }//GEN-LAST:event_txModeloFocusLost

    private void txAnoDeFabricoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txAnoDeFabricoFocusGained
  
        Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(200, 0, 20));
        lAnoDeFabrico.setForeground(new java.awt.Color(200, 0, 20));
        txAnoDeFabrico.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200),2);

        pTxAnoDeFabrico.setBorder(b);
        

//---------------------------------------
         AbstractDocument doc = (AbstractDocument) txAnoDeFabrico.getDocument();
     doc.setDocumentFilter(new DocumentFilter() {
            @Override
         public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
           try{
            int i = Integer.parseInt(newText);
                if (newText.matches("\\d*")&& !(i>2023)) { // Verifica se newText contém apenas dígitos
                   super.replace(fb, offset, length, text, attrs);
                } else {
                   // Se o texto não for numérico, não faça nada
                    Toolkit.getDefaultToolkit().beep(); // Emita um som de erro
                }
           }catch(NumberFormatException e){
           
           }
           }
       });
    }//GEN-LAST:event_txAnoDeFabricoFocusGained

    private void txAnoDeFabricoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txAnoDeFabricoFocusLost
          javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0));
        txAnoDeFabrico.setBorder(null);
        lAnoDeFabrico.setForeground(new java.awt.Color(0, 0, 0));
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
        pTxAnoDeFabrico.setBorder(b);
    }//GEN-LAST:event_txAnoDeFabricoFocusLost

    private void txPrecoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPrecoFocusGained
      Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(20, 0, 200));
        lPreco.setForeground(new java.awt.Color(20, 0, 200));
         lMZN.setForeground(new java.awt.Color(20, 0, 200));
        txPreco.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200),2);

        pTxPreco.setBorder(b);
        

//---------------------------------------
         AbstractDocument doc = (AbstractDocument) txPreco.getDocument();
     doc.setDocumentFilter(new DocumentFilter() {
            @Override
         public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.matches("\\d*")) { // Verifica se newText contém apenas dígitos
                   super.replace(fb, offset, length, text, attrs);
                } else {
                   // Se o texto não for numérico, não faça nada
                    Toolkit.getDefaultToolkit().beep(); // Emita um som de erro
                }
           }
       });
                 
    }//GEN-LAST:event_txPrecoFocusGained

    private void txPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPrecoFocusLost
          javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0));
        txPreco.setBorder(null);
        lPreco.setForeground(new java.awt.Color(0, 0, 0));
         lMZN.setForeground(new java.awt.Color(0, 0, 0));
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
        pTxPreco.setBorder(b);
    }//GEN-LAST:event_txPrecoFocusLost

    private void txPrecoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPrecoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPrecoKeyPressed

    private void txPrecoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPrecoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txPrecoKeyTyped

    private void txAnoDeFabricoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txAnoDeFabricoKeyTyped
        if(txAnoDeFabrico.getText().length()==4){
         Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(20, 0, 200));
        lAnoDeFabrico.setForeground(new java.awt.Color(20, 0, 200));
        txAnoDeFabrico.setBorder(a);}
    }//GEN-LAST:event_txAnoDeFabricoKeyTyped

    private void txNumMotorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txNumMotorFocusGained
     Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(20, 0, 200));
        lNumMotor.setForeground(new java.awt.Color(20, 0, 200));
         
        txNumMotor.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200),2);

        pTxNumMotor.setBorder(b);
        

//---------------------------------------
         AbstractDocument doc = (AbstractDocument) txNumMotor.getDocument();
     doc.setDocumentFilter(new DocumentFilter() {
            @Override
         public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.matches("\\d*")) { // Verifica se newText contém apenas dígitos
                   super.replace(fb, offset, length, text, attrs);
                } else {
                   // Se o texto não for numérico, não faça nada
                    Toolkit.getDefaultToolkit().beep(); // Emita um som de erro
                }
           }
       });
                 
 
    }//GEN-LAST:event_txNumMotorFocusGained

    private void txNumMotorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txNumMotorFocusLost
          javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0));
        txNumMotor.setBorder(null);
        lNumMotor.setForeground(new java.awt.Color(0, 0, 0));
        
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
        pTxNumMotor.setBorder(b);
    }//GEN-LAST:event_txNumMotorFocusLost

    private void txNumMotorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNumMotorKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumMotorKeyTyped

    private void txNumchassiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txNumchassiFocusGained
    Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(20, 0, 200));
        lNumMotor.setForeground(new java.awt.Color(20, 0, 200));
         
        txNumMotor.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200),2);

        pTxNumMotor.setBorder(b);
        

//---------------------------------------
         AbstractDocument doc = (AbstractDocument) txNumMotor.getDocument();
     doc.setDocumentFilter(new DocumentFilter() {
            @Override
         public void replace(DocumentFilter.FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
            String newText = fb.getDocument().getText(0, fb.getDocument().getLength()) + text;
                if (newText.matches("\\d*")) { // Verifica se newText contém apenas dígitos
                   super.replace(fb, offset, length, text, attrs);
                } else {
                   // Se o texto não for numérico, não faça nada
                    Toolkit.getDefaultToolkit().beep(); // Emita um som de erro
                }
           }
       });
 
    }//GEN-LAST:event_txNumchassiFocusGained

    private void txNumchassiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txNumchassiFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumchassiFocusLost

    private void txNumchassiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNumchassiKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumchassiKeyTyped

    private void txPreco1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPreco1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txPreco1FocusGained

    private void txPreco1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txPreco1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txPreco1FocusLost

    private void txPreco1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPreco1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txPreco1KeyPressed

    private void txPreco1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPreco1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txPreco1KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private combo_suggestion.ComboBoxSuggestion cCategoria;
    private combo_suggestion.ComboBoxSuggestion cTipCombustivel;
    private combo_suggestion.ComboBoxSuggestion cTracao;
    private javax.swing.JLabel lAnoDeFabrico;
    private javax.swing.JLabel lMZN;
    private javax.swing.JLabel lMZN1;
    private javax.swing.JLabel lMarca;
    private javax.swing.JLabel lModelo;
    private javax.swing.JLabel lNumChassi;
    private javax.swing.JLabel lNumMotor;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lPreco1;
    private javax.swing.JLabel lTipCombus;
    private javax.swing.JLabel lTipCombus1;
    private javax.swing.JLabel lTipCombus2;
    private javax.swing.JLabel lTitle;
    private javax.swing.JPanel pCTipCOmbus;
    private javax.swing.JPanel pCTipCOmbus1;
    private javax.swing.JPanel pCTipCOmbus2;
    private javax.swing.JPanel pTxAnoDeFabrico;
    private javax.swing.JPanel pTxMarca;
    private javax.swing.JPanel pTxModelo;
    private javax.swing.JPanel pTxNumChassi;
    private javax.swing.JPanel pTxNumMotor;
    private javax.swing.JPanel pTxPreco;
    private javax.swing.JPanel pTxPreco1;
    private javax.swing.JTextField txAnoDeFabrico;
    private javax.swing.JTextField txMarca;
    private javax.swing.JTextField txModelo;
    private javax.swing.JTextField txNumMotor;
    private javax.swing.JTextField txNumchassi;
    private javax.swing.JTextField txPreco;
    private javax.swing.JTextField txPreco1;
    // End of variables declaration//GEN-END:variables
}
