/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Gerente;

import DAO.PrestacoesDAO;
import Model.Prestacoes;
import View.GerenteFrame;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.Color;
import java.awt.Insets;

/**
 *
 * @author Pedro
 */
public class GerenciamentoDeprestacoes extends javax.swing.JPanel {

    GerenteFrame frame;
    Prestacoes perta;
    public GerenciamentoDeprestacoes( GerenteFrame frame, Prestacoes perta) {
        this.frame = frame;
        this.perta = perta;
        initComponents();
        //-----------------------------------------------------------------------------------------------------
         Insets insets = new Insets(1, 1, 1, 1);
         p1.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
                  p2.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
         p3.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
         p4.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
         p5.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
         p6.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
         p7.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
         p8.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
         //------------------------------------------------------------------------------------------------------
         
         
         //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        txValor.setVisible(false);
        lValor.setVisible(false);
        btConfirmar.setVisible(false);
        //++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        
        
        //=========================================================
        lbA1.setText("Data: "+perta.getVenda().getDiaDaVenda()+" De"+ perta.getVenda().getMesDaVenda()+" de "+perta.getVenda().getAnoDaVenda());
        lbA2.setText(" Preco Total a Pagar "+perta.getVenda().getPrecoDaVenda());
        lbA3.setText("Funcionario Responsavel pela venda : "+perta.getVenda().getFuncionario().getNome()+" "+perta.getVenda().getFuncionario().getApelido());
                      //-------------
       lbB1.setText(perta.getVenda().getCliente().getNome()+" "+perta.getVenda().getCliente().getApelido());
       lbB2.setText(" Nacionalidade "+perta.getVenda().getCliente().getNaturalidade());
       lbB3.setText("E-mail "+perta.getVenda().getCliente().geteMail());
                             //----------------------------
                             
           lbC1.setText(perta.getVenda().getCarro().getFabricante()+" "+perta.getVenda().getCarro().getModelo()+" "+perta.getVenda().getCarro().getAnoDeFabrico());
           lbC2.setText("Num Chassi: "+perta.getVenda().getCarro().getNumChassi()+" Num Motor "+perta.getVenda().getCarro().getNumMotor());
           lbC3.setText(perta.getVenda().getCarro().getQuilometosPercoridos()+" KM Percoridos");
           
           
           lbPor.setText(String.valueOf(perta.percentagemPago()));
           lbPagar.setText(String.valueOf(perta.getValorAPagar()));
           lbPago.setText(String.valueOf(perta.getValorPago()));
           
//==========================================================
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p1 = new javax.swing.JPanel();
        lbA2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbA3 = new javax.swing.JLabel();
        lbA1 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbC2 = new javax.swing.JLabel();
        lbC3 = new javax.swing.JLabel();
        lbC1 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbB2 = new javax.swing.JLabel();
        lbB3 = new javax.swing.JLabel();
        lbB1 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        lbPor = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        p6 = new javax.swing.JPanel();
        lbPagar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p7 = new javax.swing.JPanel();
        lbPago = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        p8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txValor = new javax.swing.JTextField();
        lValor = new javax.swing.JLabel();
        btConfirmar = new javax.swing.JButton();

        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(1000, 620));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbA2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbA2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbA2.setText("A");
        lbA2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel14.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Informacoes da Venda");
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbA3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbA3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbA3.setText("A");
        lbA3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbA1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbA1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbA1.setText("A");
        lbA1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbA3, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(lbA1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(lbA2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(lbA1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lbA2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbA3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );

        add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 270, 290));

        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informacoes Do carro");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbC2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbC2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbC2.setText("A");
        lbC2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbC3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbC3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbC3.setText("A");
        lbC3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbC1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbC1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbC1.setText("A");
        lbC1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbC2, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(lbC3, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(lbC1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                .addContainerGap())
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbC1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbC2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbC3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 280, -1));

        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Informacoes do Cliente");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbB2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbB2.setText("A");
        lbB2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbB3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbB3.setText("A");
        lbB3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbB1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbB1.setText("A");
        lbB1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addComponent(lbB3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(lbB2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(lbB1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lbB1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbB2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbB3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 280, -1));

        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Preogresso");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        p4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 210, 30));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("valor a Pago");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        p4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 310, 30));

        p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbPor.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        lbPor.setText("100.00");

        jLabel13.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel13.setText("%");

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbPor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p5Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPor, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        p4.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 210, 200));

        p6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbPagar.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbPagar.setText("0000000000000");

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel10.setText("MT");

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lbPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(7, 7, 7))
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p6Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lbPagar))
                    .addGroup(p6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 5, Short.MAX_VALUE))
        );

        p4.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 320, 80));

        p7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbPago.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        lbPago.setText("000000000000000");

        jLabel8.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel8.setText("MT");

        javax.swing.GroupLayout p7Layout = new javax.swing.GroupLayout(p7);
        p7.setLayout(p7Layout);
        p7Layout.setHorizontalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lbPago, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap())
        );
        p7Layout.setVerticalGroup(
            p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(p7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPago))
                .addContainerGap())
        );

        p4.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 320, 80));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("valor a Pagar");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel6.setInheritsPopupMenu(false);
        p4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 320, 30));

        p8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel11.setText("Pagar prestacao");

        jButton2.setText("Pagar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lValor.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        lValor.setText("Valor :");

        btConfirmar.setText("Confirmar");
        btConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p8Layout = new javax.swing.GroupLayout(p8);
        p8.setLayout(p8Layout);
        p8Layout.setHorizontalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                .addGroup(p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p8Layout.createSequentialGroup()
                        .addComponent(lValor, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        p8Layout.setVerticalGroup(
            p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lValor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p8Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addGroup(p8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p8Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(p8Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btConfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        p4.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 660, 110));

        add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 930, 260));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txValor.setVisible(true);
        lValor.setVisible(true);
        btConfirmar.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfirmarActionPerformed
perta.pagarPrestacao(Double.parseDouble(txValor.getText()));

        PrestacoesDAO aO = new PrestacoesDAO();
        aO.update(perta);
        btConfirmar.setVerifyInputWhenFocusTarget(false);
txValor.setVisible(false);
    }//GEN-LAST:event_btConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConfirmar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lValor;
    private javax.swing.JLabel lbA1;
    private javax.swing.JLabel lbA2;
    private javax.swing.JLabel lbA3;
    private javax.swing.JLabel lbB1;
    private javax.swing.JLabel lbB2;
    private javax.swing.JLabel lbB3;
    private javax.swing.JLabel lbC1;
    private javax.swing.JLabel lbC2;
    private javax.swing.JLabel lbC3;
    private javax.swing.JLabel lbPagar;
    private javax.swing.JLabel lbPago;
    private javax.swing.JLabel lbPor;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel p8;
    private javax.swing.JTextField txValor;
    // End of variables declaration//GEN-END:variables
}
