/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Gerente;

import DAO.PrestacoesDAO;
import Model.Carro;
import Model.Prestacoes;
import View.GerenteFrame;
import com.formdev.flatlaf.ui.FlatLineBorder;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Insets;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro
 */
public class ListarPrestacoes extends javax.swing.JPanel {

    DefaultTableModel model;
    GerenteFrame frame ; 
       ArrayList<Prestacoes> openFile;
       Prestacoes prestacoes;
    public ListarPrestacoes(GerenteFrame frame) {
        this.frame = frame;
        initComponents();
         Insets insets = new Insets(1, 1, 1, 1);
         p1.setBorder(new FlatLineBorder(insets, new Color(78, 170, 82), 2, 111));
        
          model = new DefaultTableModel();
		model.addColumn("ID-Cliente");
		model.addColumn("Nome");
		model.addColumn("Apelido");
		model.addColumn("Carro");
		model.addColumn("Preco");
                Tabela.setModel(model);
                PrestacoesDAO aO = new PrestacoesDAO();
                  openFile = aO.openFile();
                System.out.println(openFile.size());
                  for(Prestacoes c : openFile){
        
        model.addRow(new Object[] {   c.getVenda().getCliente().getId(), c.getVenda().getCliente().getNome(),c.getVenda().getCliente().getApelido(),c.getVenda().getCarro().getFabricante(),c.getValorAPagar()});
        
        }
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbA = new javax.swing.JLabel();
        lbC = new javax.swing.JLabel();
        lbB = new javax.swing.JLabel();
        lbF = new javax.swing.JLabel();
        lbD = new javax.swing.JLabel();
        lbE = new javax.swing.JLabel();

        setToolTipText("");
        setMinimumSize(new java.awt.Dimension(1000, 620));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 620));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 34, 495, 36));
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(546, 34, -1, 36));

        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabela);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 580, 500));

        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setText("Dados Da Venda");
        p1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 7, 227, 41));

        jButton2.setText("Gerir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        p1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 503, 175, 33));

        lbA.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbA.setText("a");
        p1.add(lbA, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 60, 300, 34));

        lbC.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbC.setText("d");
        p1.add(lbC, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 300, 34));

        lbB.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbB.setText("b");
        p1.add(lbB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 300, 34));

        lbF.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbF.setText("g");
        p1.add(lbF, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 300, 40));

        lbD.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbD.setText("e");
        p1.add(lbD, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 300, 40));

        lbE.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        lbE.setText("f");
        p1.add(lbE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 300, 40));

        add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 30, 320, 570));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      GerenciamentoDeprestacoes p1 = new GerenciamentoDeprestacoes(frame,prestacoes);
        p1.setSize(1000, 620);
        p1.setLocation(0,0);
        frame.getContente().setLayout(new BorderLayout());
        frame.getContente().removeAll();
       frame.getContente().add(p1, BorderLayout.CENTER );
       frame.getContente().revalidate();
       frame.getContente().repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        for (int i=0;i<openFile.size();i++) {
            
            if(i==Tabela.getSelectedRow()){
                prestacoes= openFile.get(i);
            lbA.setText(" Cliente: "+openFile.get(i).getVenda().getCliente().getNome()+" "+openFile.get(i).getVenda().getCliente().getApelido()+" ID "+openFile.get(i).getVenda().getCliente().getId());
            lbB.setText(" Pagamemento do "+openFile.get(i).getVenda().getCarro().getFabricante()+" "+openFile.get(i).getVenda().getCarro().getModelo()+" "+openFile.get(i).getVenda().getCarro().getAnoDeFabrico());
            lbC.setText("Orcamento estimado em "+ openFile.get(i).getVenda().getPrecoDaVenda()+" MZN");
            lbD.setText("Dos Quais "+openFile.get(i).getValorPago()+" MZN"+" Foram Pagos")
                    ;
            lbE.setText("Falta Apenas "+openFile.get(i).getValorAPagar()+" Mzn");
            lbF.setText("Data da Primeira Prestacao: "+ openFile.get(i).getVenda().getDiaDaVenda());
            }
            
        }
        
        
    }//GEN-LAST:event_TabelaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabela;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbA;
    private javax.swing.JLabel lbB;
    private javax.swing.JLabel lbC;
    private javax.swing.JLabel lbD;
    private javax.swing.JLabel lbE;
    private javax.swing.JLabel lbF;
    private javax.swing.JPanel p1;
    // End of variables declaration//GEN-END:variables
}
