/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.border.Border;

/**
 *
 * @author Pedro
 */
public class AddFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form AddFuncionario
     */
    public AddFuncionario() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        pTxNome = new javax.swing.JPanel();
        txSalario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pTxApelido = new javax.swing.JPanel();
        txApelido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        pTxNome1 = new javax.swing.JPanel();
        txnome1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        btGuardar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Adicionar Funcionario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 360, 60));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Dados Pessoais :");
        jLabel3.setToolTipText("");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Estado Civil");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        jComboBox1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro/a", "Casado/a", "Divorciado/a", "Viuvo/a" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 30));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 300, 50));

        pTxNome.setBackground(new java.awt.Color(255, 255, 255));
        pTxNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxNome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txSalario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txSalario.setBorder(null);
        txSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txSalarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txSalarioFocusLost(evt);
            }
        });
        txSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txSalarioActionPerformed(evt);
            }
        });
        pTxNome.add(txSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 170, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Salario");
        jLabel4.setToolTipText("");
        pTxNome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        jLabel10.setFont(new java.awt.Font("Roboto Medium", 1, 18)); // NOI18N
        jLabel10.setText("$");
        pTxNome.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 30));

        add(pTxNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 300, 50));

        pTxApelido.setBackground(new java.awt.Color(255, 255, 255));
        pTxApelido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxApelido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txApelido.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txApelido.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txApelido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txApelidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txApelidoFocusLost(evt);
            }
        });
        txApelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txApelidoActionPerformed(evt);
            }
        });
        pTxApelido.add(txApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Apelido:");
        jLabel5.setToolTipText("");
        pTxApelido.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        add(pTxApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 300, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Especialidade");
        jLabel6.setToolTipText("");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        jComboBox2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vendedor", "Gerente", "Outro" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 170, 30));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 300, 50));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Nacionalidade");
        jLabel7.setToolTipText("");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 20));

        jComboBox3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mocambicana", "Outra" }));
        jComboBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 30));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 300, 50));

        pTxNome1.setBackground(new java.awt.Color(255, 255, 255));
        pTxNome1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pTxNome1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txnome1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txnome1.setBorder(null);
        txnome1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txnome1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txnome1FocusLost(evt);
            }
        });
        pTxNome1.add(txnome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 210, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel8.setText("Nome:");
        jLabel8.setToolTipText("");
        pTxNome1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        add(pTxNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 300, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel9.setText("Sexo");
        jLabel9.setToolTipText("");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 20));

        jComboBox4.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "Masculino", "Feminino" }));
        jComboBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel4.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 220, 30));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 300, 50));

        btGuardar.setBackground(new java.awt.Color(204, 204, 204));
        btGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btGuardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btGuardarMouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        jLabel11.setText("Guardar");

        javax.swing.GroupLayout btGuardarLayout = new javax.swing.GroupLayout(btGuardar);
        btGuardar.setLayout(btGuardarLayout);
        btGuardarLayout.setHorizontalGroup(
            btGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btGuardarLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(85, 85, 85))
        );
        btGuardarLayout.setVerticalGroup(
            btGuardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btGuardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(btGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 230, 50));

        jButton1.setText("jButton1");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 510, 260, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txSalarioActionPerformed

    private void txApelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txApelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txApelidoActionPerformed

    private void txSalarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txSalarioFocusGained
       
        Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(20, 0, 200));
        txSalario.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200));
        pTxNome.setBorder(b);
    }//GEN-LAST:event_txSalarioFocusGained

    private void txSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txSalarioFocusLost
    javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0));
     txSalario.setBorder(null);
    Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
      pTxNome.setBorder(b);
    }//GEN-LAST:event_txSalarioFocusLost

    private void txApelidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txApelidoFocusGained
       Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(20, 0, 200));
        txApelido.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200));
        pTxApelido.setBorder(b);
    }//GEN-LAST:event_txApelidoFocusGained

    private void txApelidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txApelidoFocusLost
       javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0));
     txApelido.setBorder(null);
    Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
      pTxApelido.setBorder(b);
    }//GEN-LAST:event_txApelidoFocusLost

    private void txnome1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txnome1FocusGained
       Border a=  javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(20, 0, 200));
        txnome1.setBorder(a);
        Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 0, 200));
        pTxNome1.setBorder(b);
    }//GEN-LAST:event_txnome1FocusGained

    private void txnome1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txnome1FocusLost
         javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0));
     txnome1.setBorder(null);
    Border b = javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0));
      pTxNome1.setBorder(b);
    }//GEN-LAST:event_txnome1FocusLost

    private void btGuardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGuardarMouseEntered
       a= btGuardar.getBackground();
        btGuardar.setBackground(Color.GREEN);
      
    }//GEN-LAST:event_btGuardarMouseEntered

    private void btGuardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGuardarMouseExited
          btGuardar.setBackground(a);
    }//GEN-LAST:event_btGuardarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btGuardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel pTxApelido;
    private javax.swing.JPanel pTxNome;
    private javax.swing.JPanel pTxNome1;
    private javax.swing.JTextField txApelido;
    private javax.swing.JTextField txSalario;
    private javax.swing.JTextField txnome1;
    // End of variables declaration//GEN-END:variables
public  Color a ;

}
