/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.AdminController;
import DAO.AdminDao;
import DAO.ImagemDirectorioDAO;
import Model.Admin;
import Model.Funcionario;
import Model.ImagemDirectorios;
import ViewFuncionario.Base;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatGitHubIJTheme;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Pedro
 */
public class LoginP extends javax.swing.JFrame {
  
    AdminDao adminDao ;
    ImageIcon icon ;
    ArrayList<Admin> openFile ;
      ArrayList<Funcionario> sellectAllFuncionario;
    public LoginP() throws SQLException, ClassNotFoundException {
        adminDao = new AdminDao();
         openFile = adminDao.openFile();
         Calendar c = Calendar.getInstance();
         System.out.println(c.getTime().toString());
        UIManager.put("PasswordField.capsLockIconColor", "#B92303");
        UIManager.put("PasswordField.showRevealButton", true);
   //   UIManager.put( "Button.arc" , 999 );
        initComponents();
        
         Controller.AdminController cc= new AdminController(this);
        sellectAllFuncionario = cc.sellectAllFuncionario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pfSenha = new textfield.PasswordField();
        txEmail = new textfield.TextField();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LogIn");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pfSenha.setLabelText("Senha :");
        pfSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfSenhaActionPerformed(evt);
            }
        });

        txEmail.setLabelText("E-Mail");
        txEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEmailActionPerformed(evt);
            }
        });

        jButton1.setText("entrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pfSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(txEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(pfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txEmailActionPerformed

    private void pfSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfSenhaActionPerformed

    }//GEN-LAST:event_pfSenhaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Funcionario object = null;
        
        for(Funcionario f : sellectAllFuncionario){
   if(f.geteMail().equalsIgnoreCase(txEmail.getText())){
   object = f;
   
   }
   }
   
   if(object!=null&&object.getEspecialidade().equalsIgnoreCase("Gerente")){
   String senha = new String(pfSenha.getPassword()).trim();
   if(senha.equalsIgnoreCase(object.getSenha())){
       ImagemDirectorioDAO dao = new ImagemDirectorioDAO();
        String teste= object.getIdentidade();
         ImagemDirectorioDAO img = new ImagemDirectorioDAO();
            ArrayList<ImagemDirectorios> openFile = img.openFile("Imagens");
              for (int i=0; i<openFile.size();i++){
                  
              if(teste.equalsIgnoreCase(openFile.get(i).getIdentidade())){
             
                  new GerenteFrame(openFile.get(i).getIcon(), object).setVisible(true);
                  this.dispose();
              }
                  }
   }else{JOptionPane.showMessageDialog(rootPane, "Usuario ou senha Incorrectos", "Erro Autenticacao", JOptionPane.ERROR_MESSAGE);}
   }else if(object!=null&&object.getEspecialidade().equalsIgnoreCase("Vendedor")){
   
    String senha = new String(pfSenha.getPassword()).trim();
   if(senha.equalsIgnoreCase(object.getSenha())){
       ImagemDirectorioDAO dao = new ImagemDirectorioDAO();
        String teste= object.getIdentidade();
         ImagemDirectorioDAO img = new ImagemDirectorioDAO();
            ArrayList<ImagemDirectorios> openFile = img.openFile("Imagens");
              for (int i=0; i<openFile.size();i++){
                  
              if(teste.equalsIgnoreCase(openFile.get(i).getIdentidade())){
             
                  new Base(openFile.get(i).getIcon(), object).setVisible(true);
                  this.dispose();
              }
                  }
   }else{JOptionPane.showMessageDialog(rootPane, "Usuario ou senha Incorrectos", "Erro Autenticacao", JOptionPane.ERROR_MESSAGE);}
   
   }else if(txEmail.getText().equalsIgnoreCase(openFile.get(0).getE_mail())){
      
       String senha = new String(pfSenha.getPassword()).trim();
       if(senha.equalsIgnoreCase(openFile.get(0).getSenha())){
       new  ADMFrame(openFile.get(0)).setVisible(true);
        this.dispose();
       }else{
    JOptionPane.showMessageDialog(rootPane, "Usuario ou senha Incorrectos", "Erro Autenticacao", JOptionPane.ERROR_MESSAGE);   
       
       }
       
   }else {
            JOptionPane.showMessageDialog(rootPane, "Usuario ou senha Incorrectos", "Erro Autenticacao", JOptionPane.ERROR_MESSAGE);
           }
   
   

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
           // FlatIntelliJLaf.registerCustomDefaultsSource("style");
// FlatGitHubIJTheme.setup();
            UIManager.setLookAndFeel(new FlatGitHubIJTheme());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(LoginP.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LoginP().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(LoginP.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(LoginP.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private textfield.PasswordField pfSenha;
    private textfield.TextField txEmail;
    // End of variables declaration//GEN-END:variables
}
